### PR TITLE
fixed issue #78: inconsistencies between std and adj/ekey as well as refactored tc code to have tc and tc_iter in separate files

### PR DESCRIPTION
**Pull request by JackLiJXL**

### CODE REVIEW

**Comment by JackLiJXL** [comment]
also gets branch up to date with mt_api for some commits

**Comment by apricot2012** [comment]
I also created a test_concurrency.cpp in the testing folder in my newest PR -- maybe we can stick to that?

**Comment by JackLiJXL** [comment]
yes^^

**Comment by JackLiJXL** [comment]
sounds good

**Pull request merged**
